#include "UIConfig.h"

UIConfig g_uiCfg = {
    .bg          = 0x0000,
    .text        = 0xFFFF,
    .subtext     = 0x8410,
    .ok          = 0x07E0,
    .warn        = 0xFD20,
    .danger      = 0xF800,
    .accent      = 0x07FF,
    .header      = 0x1926,
    .surface     = 0x18C3,
    .btn_ok      = 0x0640,
    .btn_back    = 0x2945,
    .brightness  = 220,
    .warning_days = 7,
    .danger_days  = 3,
    .tbtn_h         = 48,
    .cat_cols       = 2,
    .cat_gap        = 6,
    .list_item_h    = 64,
    .btn_radius     = 10,
    .tbtn_margin    = 8,
    .list_radius    = 6,
    .sub_hdr_h      = 54,
    .cat_hdr_h      = 44,
    .power_save_min = 10,
    .date_format    = 0,
    .show_clock     = 1,
    .sound_ok       = 1,
    .sound_err      = 1,
};
